### ISSUE TITLE
ConvertFromSLARecord#convert should not be a void method

### ISSUE THREAD

**Issue by ricoapon** [wverveer/SLA-report#26]
**Describe the bug**
ConvertFromSLARecord#convert returns a void. This means that it will convert the output and write to a file. However, this is a violation of the single responsibility principle.

**Expected behavior**
ConvertFromSLARecord It should only convert and not write to a file. Writing to a file should be done in another class.

**Comment by lyberakis** [comment]
After our team meeting, we decided to change ConvertFromSLARecord.convert method to return a list of Strings that will then be picked up by a writer class, whose responsibility will be to write to the CSV or HTML file of the output.
